version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      - MONGO_URI='mongodb://mongo:27017/vai-challenge'
      - PORT=3000
      - API_KEY=lMaScshrjA81x89hM1IPx7xVWFa9HWlZ1quUm5xQ
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
